### PR TITLE
fix: concurrent threading issue

### LINKED ISSUE #115: Bug: crash when creating multiple clients on iOS
### Describe the bug

I'm working on multi account on Converse and need to instantiate multiple xmtp clients when opening the app
I experienced some crashes in the swift code at different places when I did `createFromKeyBundle`, always EXC_BAD_EXEC:

Here:
 
Capture d’écran 2023-09-14 à 18 23 44

And also here:

Capture d’écran 2023-09-14 à 18 38 00

when settings codecs[codec.id] for instance.

To reproduce I just did 
```
for (let index = 0; index < 200; index++) {
            Client.createRandom();
            console.log(index);
          }
```
and I have the crash every time

Looks like a thread safety issue maybe? I tried forcing those lines on main thread and it works but honestly I have no idea why:
Capture d’écran 2023-09-14 à 18 38 42
Capture d’écran 2023-09-14 à 18 38 52

N.B.: it seems that I don't have the error if I never launch multiple `createFromKeyBundle` or `createRandom` in // (just by adding an `await` before each `createRandom` call) it's not ideal and also the SDK should never make the app crash so it's worth exploring

### Expected behavior

_No response_

### Steps to reproduce the bug

_No response_

### PR DESCRIPTION
**Pull request by nplasterer**
Fixes https://github.com/xmtp/xmtp-react-native/issues/115

### CODE REVIEW

**Review by neekolas — APPROVED** [review]

File: ios/XMTPModule.swift [hunk 1]
```diff
@@ -70,10 +70,52 @@ extension Conversation {
...
+        // A method to update the conversations
+        func updateClient(key: String, client: XMTP.Client?) {
+            clients[key] = client
+        }
+
+        // A method to retrieve a conversation
+        func getClient(key: String) -> XMTP.Client? {
+            return clients[key]
+        }
+    }
```
Comment (nakajima) [inline ios/XMTPModule.swift:90]: Instead of wrapping these objects, could we just keep the dictionaries and use the `updateValue` function:

```swift
await clients.updateValue(client, forKey: "some address")
``` 

then we can just use the normal subscript getters.

**Review by nakajima — APPROVED** [review]
