### PR TITLE
Return last message if passed as group option

### LINKED ISSUE #513: Bug: Last Message is not exposed in Group type when last message is included in list groups
### Describe the bug

In Group.ts lastMessage is not being exposed when returned from the listGroups method

### Expected behavior

Last message is exposed and decrypted

### Steps to reproduce the bug

_No response_

### PR DESCRIPTION
**Pull request by nplasterer**
Closes https://github.com/xmtp/xmtp-react-native/issues/513

### CODE REVIEW

File: android/src/main/java/expo/modules/xmtpreactnativesdk/XMTPModule.kt [hunk 1]
```diff
@@ -635,7 +635,7 @@ class XMTPModule : Module() {
                 val sortedGroupList = if (order == ConversationOrder.LAST_MESSAGE) {
                     client.conversations.listGroups()
                         .sortedByDescending { group ->
-                            group.decryptedMessages(limit = 1).firstOrNull()?.sentAt
```
Comment (nplasterer) [inline android/src/main/java/expo/modules/xmtpreactnativesdk/XMTPModule.kt:638]: I actually ran into this issue on the native side. Limit actually just picks the first message where as we want the last message. So we can't use limit here. Could be an improvement in libxmtp to allow the order to be passed as a parameter.

**Review by alexrisch — APPROVED** [review]
