### PR TITLE
Group consent state

### LINKED ISSUE #356: Bug: group.topic incorrectly returns same value as group.id
### Describe the bug

group.topic returns the group id (same value as group.id) but messages in the group have message.topic = /xmtp/mls/1/g-<GROUP-ID>/proto , I would expect group.topic to have that same value

### Expected behavior

group.topic returns the same value as message.topic does for the messages in that group: `/xmtp/mls/1/g-<GROUP-ID>/proto`

### Steps to reproduce the bug

_No response_

### PR DESCRIPTION
**Pull request by nplasterer**
Adds the consent state to group like we have for dms

Fixes https://github.com/xmtp/xmtp-react-native/issues/356

### CODE REVIEW

File: src/lib/Group.ts [hunk 1]
```diff
@@ -225,4 +226,8 @@ export class Group<
       throw e
     }
   }
+
+  async consentState(): Promise<'allowed' | 'denied' | 'unknown'> {
```
Comment (peterferguson) [inline src/lib/Group.ts:227]: Hey I am wondering whether this is the final state for the group `consentState`? 

I want to display which members of a group have accepted the group invite or not. AFAIK this can only be done on the client for now? 

If this function returned the state of each individual member then it would be easier to do directly from the network. 

Is this something that might be implemented in the future?

Comment (nplasterer) [reply src/lib/Group.ts:227]: Hmmm not sure I understand the question? Are you looking for a way that every person in the group can see if someone else has approved or denied the group? Inherently the personal private preferences are just that private and personal. So no one else in the group can decrypt if your blocked that person or group only you can.

Comment (peterferguson) [reply src/lib/Group.ts:227]: Yep exactly what I was wondering & that clarifies it.

Pending / joined members will have to just be a client-side feature in that case.

Thanks!

File: example/src/HomeScreen.tsx [hunk 2]
```diff
@@ -99,12 +99,28 @@ function GroupListItem({
   const [messages, setMessages] = useState<
     DecodedMessage<SupportedContentTypes>[]
   >([])
+  const lastMessage = messages?.[0]
+  const [getConsentState, setConsentState] = useState<string | undefined>()
```
Comment (alexrisch) [inline example/src/HomeScreen.tsx]: Normally naming conventions would be consentState

File: example/src/HomeScreen.tsx [hunk 3]
```diff
@@ -99,12 +99,28 @@ function GroupListItem({
...
+
+  const denyGroup = async () => {
+    await client?.contacts.denyGroups([group.id])
+    group
+      .consentState()
+      .then(setConsentState)
```
Comment (alexrisch) [inline example/src/HomeScreen.tsx]: This is fine to do this way, but you are already in an async function so you could also do:
```
const consent = await group
      .consentState()
      setConsentState(consent)
```

**Review by alexrisch — APPROVED** [review]
